# Generated by Django 6.0.2 on 2026-04-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetplan',
            options={'ordering': ['is_misc', 'id'], 'verbose_name': '予算内訳', 'verbose_name_plural': '予算内訳'},
        ),
    ]
