# Generated by Django 6.0.2 on 2026-04-16 04:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='実績額'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_budget',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='予算額'),
        ),
        migrations.CreateModel(
            name='BudgetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='項目名')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='実績額')),
                ('recorded_at', models.DateField(default=django.utils.timezone.now, verbose_name='計上日')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_records', to='project_management_app.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': '予算実績',
                'verbose_name_plural': '予算実績',
                'ordering': ['-recorded_at', '-id'],
            },
        ),
    ]
