# Generated by Django 6.0.2 on 2026-04-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0002_alter_budgetplan_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetplan',
            options={'verbose_name': '予算内訳', 'verbose_name_plural': '予算内訳'},
        ),
        migrations.RemoveField(
            model_name='budgetplan',
            name='is_misc',
        ),
    ]
