# Generated by Django 6.0.2 on 2026-04-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0002_alter_project_actual_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='期限'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', '担当者'), ('applicant', '申請者'), ('manager', '部門管理者'), ('hq', '本部管理者')], default='applicant', max_length=30, verbose_name='ロール'),
        ),
    ]
