# Generated by Django 6.0.2 on 2026-04-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0003_project_due_date_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_headquarters',
            field=models.BooleanField(default=False),
        ),
    ]
