# Generated by Django 6.0.2 on 2026-04-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0004_department_is_headquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
    ]
