# Generated by Django 6.0.2 on 2026-04-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0005_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='actual_amount',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', 'タスク担当者'), ('applicant', '申請者'), ('manager', '部門管理者'), ('hq', '本部管理者')], default='applicant', max_length=30, verbose_name='ロール'),
        ),
    ]
