# Generated by Django 6.0.2 on 2026-04-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0006_remove_project_actual_amount_alter_customuser_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.UniqueConstraint(fields=('project', 'level'), name='unique_approval_per_project_level'),
        ),
    ]
