# Generated by Django 6.0.2 on 2026-04-22 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0009_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'コメント', 'verbose_name_plural': 'コメント'},
        ),
    ]
