# Generated by Django 6.0.2 on 2026-04-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0010_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_budget_notified',
            field=models.BooleanField(default=False),
        ),
    ]
