# Generated by Django 6.0.2 on 2026-04-22 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0011_project_is_budget_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='費目')),
                ('planned_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='予定額')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plans', to='project_management_app.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': '予算内訳',
                'verbose_name_plural': '予算内訳',
            },
        ),
    ]
