# Generated by Django 6.0.2 on 2026-04-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0012_budgetplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrecord',
            name='category',
            field=models.CharField(max_length=100, null=True, verbose_name='カテゴリ'),
        ),
    ]
